# Generated by Django 2.2.12 on 2020-04-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstMsbvee12Apr2020',
            fields=[
                ('fid_1', models.AutoField(primary_key=True, serialize=False)),
                ('fid', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, db_column='Category', max_length=254, null=True)),
                ('specify_if', models.CharField(blank=True, max_length=254, null=True)),
                ('dvet_inst_field', models.CharField(blank=True, db_column='dvet_inst_', max_length=254, null=True)),
                ('inst_name', models.CharField(blank=True, max_length=254, null=True)),
                ('inst_type', models.CharField(blank=True, max_length=254, null=True)),
                ('location', models.CharField(blank=True, db_column='Location', max_length=254, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=254, null=True)),
                ('area_name', models.CharField(blank=True, max_length=254, null=True)),
                ('city_villa', models.CharField(blank=True, max_length=254, null=True)),
                ('district', models.CharField(blank=True, max_length=254, null=True)),
                ('taluka', models.CharField(blank=True, max_length=254, null=True)),
                ('pincode', models.BigIntegerField(blank=True, db_column='Pincode', null=True)),
                ('photo_of_t', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'inst_msbvee_12apr2020',
                'managed': False,
            },
        ),
    ]
