# Generated by Django 3.0.5 on 2020-07-23 12:13

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospbeds',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.PointField(default='POINT(0.0 0.0)', srid=4326)),
                ('factly_nam', models.CharField(default='None', max_length=254)),
                ('totalbeds', models.BigIntegerField(blank=True, null=True)),
                ('ncv', models.BigIntegerField(blank=True, null=True)),
                ('nco', models.BigIntegerField(blank=True, null=True)),
                ('nci', models.BigIntegerField(blank=True, null=True)),
                ('cvv', models.BigIntegerField(blank=True, null=True)),
                ('cov', models.BigIntegerField(blank=True, null=True)),
                ('civ', models.BigIntegerField(blank=True, null=True)),
                ('cvr', models.BigIntegerField(blank=True, null=True)),
                ('cor', models.BigIntegerField(blank=True, null=True)),
                ('cir', models.BigIntegerField(blank=True, null=True)),
                ('cvo', models.BigIntegerField(blank=True, null=True)),
                ('coo', models.BigIntegerField(blank=True, null=True)),
                ('cio', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
    ]
