# Generated by Django 3.0.5 on 2020-07-23 13:02

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CovidHospbeds',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('factly_nam', models.CharField(default='None', max_length=254)),
                ('totalbeds', models.BigIntegerField(blank=True, null=True)),
                ('ncv', models.BigIntegerField()),
                ('nco', models.BigIntegerField(blank=True, null=True)),
                ('nci', models.BigIntegerField(blank=True, null=True)),
                ('cvv', models.BigIntegerField(blank=True, null=True)),
                ('cov', models.BigIntegerField(blank=True, null=True)),
                ('civ', models.BigIntegerField(blank=True, null=True)),
                ('cvr', models.BigIntegerField(blank=True, null=True)),
                ('cor', models.BigIntegerField(blank=True, null=True)),
                ('cir', models.BigIntegerField(blank=True, null=True)),
                ('cvo', models.BigIntegerField(blank=True, null=True)),
                ('coo', models.BigIntegerField(blank=True, null=True)),
                ('cio', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Hospbeds',
        ),
    ]
