# Generated by Django 3.0.5 on 2020-07-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200723_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidhospbeds',
            name='ncv',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='covidhospbeds',
            name='totalbeds',
            field=models.BigIntegerField(default=0),
        ),
    ]
